export const BADGE_TOP_POSITION = -15;
export const BADGE_LEFT_POSITION = 10;
export const BADGE_ANIMATION_DURATION = 100;
export const BADGE_MAX_DEFAULT_VALUE = 100;
export const BADGE_DEFAULT_RADIUS = 10;
