export const SWITCH_CONTAINER_HEIGHT_SMALL = 20;
export const SWITCH_CONTAINER_WIDTH_SMALL = 40;
export const SWITCH_THUMB_WIDTH_SMALL = 17;
export const SWITCH_THUMB_HEIGHT_SMALL = 17;

export const SWITCH_CONTAINER_HEIGHT_MEDIUM = 25;
export const SWITCH_CONTAINER_WIDTH_MEDIUM = 45;
export const SWITCH_THUMB_WIDTH_MEDIUM = 22;
export const SWITCH_THUMB_HEIGHT_MEDIUM = 22;

export const SWITCH_CONTAINER_HEIGHT_LARGE = 30;
export const SWITCH_CONTAINER_WIDTH_LARGE = 50;
export const SWITCH_THUMB_WIDTH_LARGE = 26;
export const SWITCH_THUMB_HEIGHT_LARGE = 26;
