export const FADING_DEFAULT_INITIAL_LARGE_POSITION_VALUE = 1000;
export const FADING_DEFAULT_INITIAL_SMALL_POSITION_VALUE = 50;

export const BACK_IN_INITIAL_DEFAULT_POSITION = 1000;
export const BACK_IN_DEFAULT_DURATION = 1000;
export const BACK_IN_DEFAULT_DELAY = 0;
