export const LABELED_ANIMATION_DURATION = 120;
export const INPUT_DEFAULT_HEIGHT = 56;
export const TEXT_FONT_DEFAULT_HEIGHT = 10;
export const TRANSLATE_Y_ANIMATED_DEFAULT_POSITION = -28;
export const PLACEHOLDER_OUTLINE_LEFT_POSITION = 8;
export const PLACEHOLDER_FILED_INPUT_LEFT_POSITION = 2;
