export const LABELED_ANIMATION_DURATION = 120;
export const INPUT_DEFAULT_HEIGHT = 58;
export const PLACEHOLDER_LEFT_POSITION = 8;
export const TEXT_FONT_DEFAULT_HEIGHT = 10;
export const TRANSLATE_Y_ANIMATED_DEFAULT_POSITION = -28;
