export const SHOW_SNACK_BAR_MESSAGE = 'SHOW_SNACK_BAR_MESSAGE';
export const HIDE_SNACK_BAR_MESSAGE = 'HIDE_SNACK_BAR_MESSAGE';

export enum SNACK_BAR {
  LENGTH_SHORT = 500,
  LENGTH_MEDIUM = 800,
  LENGTH_LARGE = 2000,
}

export const SNACK_BAR_SCREEN_GAP = 25;
