export const IMAGE_ROUNDED_RADIUS = 100;
export const IMAGE_ROUNDED_SM_RADIUS = 20;
export const IMAGE_ROUNDED_MD_RADIUS = 30;
export const IMAGE_ROUNDED_LG_RADIUS = 40;
export const IMAGE_ROUNDED_XL_RADIUS = 60;
export const IMAGE_SQUARE_RADIUS = 0;
