export const ACCORDION_DETAILS_OPACITY_DURATION = 200;
export const ACCORDION_DETAILS_DEFAULT_EXPANDED = false;
export const ROTATE_ANIMATION_DURATION = 150;
export const HEIGHT_VALUE_ANIMATION_DURATION = 200;
export const ROTATE_ANIMATION_RANGE = ['0deg', '180deg'];
